### ISSUE TITLE
Projekt aus altem HHJ wird nicht in neuem HHJ angezeigt, obwohl HHT aus neuem HHJ eingetragen wurden

### ISSUE THREAD

**Issue by DieMichii** [OpenAdministration/FinanzAntragUI#168]
https://finanzen.stura.eu/projekt/754

**Comment by lukas-staab** [comment]
![image](https://user-images.githubusercontent.com/14363325/163562792-2b5cf734-52a8-428d-b975-3c4033c93861.png)
kannst du selbst ändern. Aktuell ist gar kein Titel gesetzt?
