### ISSUE TITLE
Projekt wird bei Statuswechsel nicht aus Reiter "StuRa Sitzung" gelöscht

### ISSUE THREAD

**Issue by DieMichii** [OpenAdministration/FinanzAntragUI#180]
https://finanzen.stura.eu/projekt/757

Ggf. connected to https://github.com/OpenAdministration/FinanzAntragUI/issues/168

**Comment by lukas-staab** [comment]
was soll da der Fehler sein? Braucht doch noch ne verkündung ...

**Comment by DieMichii** [comment]
grml. hast recht...
