### ISSUE TITLE
Shortlinks zeigen z.T. immer noch auf alte Webseite

### ISSUE THREAD

**Issue by DieMichii** [OpenAdministration/FinanzAntragUI#182]
Aufgefallen bei Sassi und mir:
wenn man das alte System häufiger über stura.eu/frust o.ä. aufgerufen hat, kann es passieren, dass man jetzt auch noch auf die alte Seite weitergeleitet wird.
Es wäre gut, wenn der Hinweistext für nicht-Finanzer im alten System wie folgt lauten wird:
Diese Webseite ist veraltet und nicht mehr erreichbar. Das neue Finanzsystem steht unter finanzen.stura.eu zur Verfügung.

**Comment by lukas-staab** [comment]
das ist ein Browserproblem. Das sollte weg gehen wenn man den cache des browsers leert. Den Text kann ich gerade nicht anpassen - ich habs aber mal weitergegeben
